project:
  type: website
  output-dir: docs

website: 
  title: "Nicolette van der Poel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Resume
      - Project Page
      - Free for all
      - text: Maps
        menu: 
          - text: Projects
            href: projects.qmd
          - text: Certifications
      - text: Education
        menu: 
          - text: Study Abroad
            href: study_abroad.qmd
          - text: Rowing
            href: rowing.qmd
          - text: CV
      - Events
      - Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
