project:
  type: website
  output-dir: docs

website: 
  title: "Nicolette van der Poel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Resume
      - Project Page
      - Free for all
      - Maps
      - Education
      - Events
      - Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
