project:
  type: website
  output-dir: docs

website: 
  title: "Nicolette van der Poel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Resume & CV
        href: CV.qmd
      - text: Projects
        href: projects.qmd
      - text: Maps
        href: maps.qmd
      - text: Education
        menu: 
          - text: Study Abroad
            href: study_abroad.qmd
          - text: Rowing
            href: rowing.qmd
      - text: Events

format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss
    css: styles.css
    toc: true
