---
title: "Rowing"
---

Any student-athlete can tell you the amount of time, energy, and dedication it takes to be part of a team and also a full-time student. Rowing includes many early mornings and tests to your physical and mental strength. However, it also nurtures ambition, grit, passion, power, and a strong value of teamwork. No win can happen without every single person in a boat.

# Teams

## UCSB Rowing

Under the guidance of Coach Brooke Downes, I rowed with some amazing women for my two years on the team. My time here included a rigorous 6-day practice schedule but paid off with many medals and awards! This team is truly special and contains some very powerful women with multifaceted talents and interests. Each member is not just high-achieving in their sport, but also in academics, community engagement, and extracurriculars.

## Berkeley High Crew

Berkeley High Crew introduced me to rowing when I needed it most. Rowing showed me the sheer strength of ones mind and that the human body, and ones-self, is more capable than anyone realizes. In my opinion, the same is true for other aspects of life where some accomplishments may seem impossible, but in reality require persistence, imagination and determination.






